# Generated by Django 5.1.15 on 2026-07-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_blog_article_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_posted_title', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
